server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8080/
          predicates:
            - Path=/acts/**
        - id: Microservice2
          uri: http://localhost:8081/
          predicates:
            - Path=/users/**
