server:
  port: 8002

spring:
  datasource:
    url: jdbc:h2:mem:notes_db
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  application:
    name: books

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always